# Generated by Django 3.0.6 on 2020-06-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(blank=True, verbose_name='Описание')),
                ('long_description', models.TextField(blank=True, verbose_name='Описание (html)')),
                ('latitude', models.FloatField(verbose_name='Координата широты')),
                ('longitude', models.FloatField(verbose_name='Координата долготы')),
            ],
        ),
    ]
