# Generated by Django 3.0.7 on 2020-10-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200622_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('position',)},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('place', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('latitude', 'longitude')},
        ),
    ]
