# Generated by Django 3.0.7 on 2020-10-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20201028_1412'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('place', 'position')},
        ),
    ]
